{
  "schema_version": "1.4.0",
  "id": "GHSA-9mh7-9qxg-6fpq",
  "modified": "2023-04-16T00:30:25Z",
  "published": "2023-04-16T00:30:25Z",
  "aliases": [
    "CVE-2020-27545"
  ],
  "details": "libdwarf before 20201017 has a one-byte out-of-bounds read because of an invalid pointer dereference via an invalid line table in a crafted object.",
  "severity": [

  ],
  "affected": [

  ],
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://nvd.nist.gov/vuln/detail/CVE-2020-27545"
    },
    {
      "type": "WEB",
      "url": "https://github.com/davea42/libdwarf-code/commit/95f634808c01f1c61bbec56ed2395af997f397ea"
    },
    {
      "type": "WEB",
      "url": "https://bugzilla.redhat.com/show_bug.cgi?id=2025694"
    },
    {
      "type": "WEB",
      "url": "https://sourceforge.net/projects/libdwarf/"
    },
    {
      "type": "WEB",
      "url": "https://www.prevanders.net/dwarfbug.html#DW202010-001"
    },
    {
      "type": "WEB",
      "url": "http://web.archive.org/web/20190601140703/https://sourceforge.net/projects/libdwarf/"
    }
  ],
  "database_specific": {
    "cwe_ids": [

    ],
    "severity": null,
    "github_reviewed": false,
    "github_reviewed_at": null,
    "nvd_published_at": "2023-04-16T00:15:00Z"
  }
}