{
  "schema_version": "1.4.0",
  "id": "GHSA-crhm-wc96-7579",
  "modified": "2023-08-22T21:30:27Z",
  "published": "2023-08-22T21:30:27Z",
  "aliases": [
    "CVE-2022-48565"
  ],
  "details": "An XML External Entity (XXE) issue was discovered in Python through 3.9.1. The plistlib module no longer accepts entity declarations in XML plist files to avoid XML vulnerabilities.",
  "severity": [

  ],
  "affected": [

  ],
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://nvd.nist.gov/vuln/detail/CVE-2022-48565"
    },
    {
      "type": "WEB",
      "url": "https://bugs.python.org/issue42051"
    }
  ],
  "database_specific": {
    "cwe_ids": [

    ],
    "severity": null,
    "github_reviewed": false,
    "github_reviewed_at": null,
    "nvd_published_at": null
  }
}