{
  "schema_version": "1.2.0",
  "id": "GHSA-6978-4w92-428p",
  "modified": "2022-06-16T00:00:26Z",
  "published": "2022-06-09T00:00:16Z",
  "aliases": [
    "CVE-2022-31313"
  ],
  "details": "api-res-py package in PyPI 0.1 is vulnerable to a code execution backdoor in the request package.",
  "severity": [
    {
      "type": "CVSS_V3",
      "score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H"
    }
  ],
  "affected": [

  ],
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://nvd.nist.gov/vuln/detail/CVE-2022-31313"
    },
    {
      "type": "WEB",
      "url": "https://github.com/rakeshrkz7/as_api_res/issues/1"
    },
    {
      "type": "WEB",
      "url": "https://pypi.org/project/api-res-py/"
    },
    {
      "type": "WEB",
      "url": "http://pypi.doubanio.com/simple/request"
    }
  ],
  "database_specific": {
    "cwe_ids": [

    ],
    "severity": "CRITICAL",
    "github_reviewed": false
  }
}