{
  "schema_version": "1.2.0",
  "id": "GHSA-q6w2-jxcm-2crj",
  "modified": "2022-06-09T23:51:03Z",
  "published": "2022-05-17T05:47:38Z",
  "aliases": [
    "CVE-2008-7263"
  ],
  "summary": "Improper Authentication in pyftpdlib",
  "details": "ftpserver.py in pyftpdlib before 0.5.0 does not delay its response after receiving an invalid login attempt, which makes it easier for remote attackers to obtain access via a brute-force attack.",
  "severity": [
    {
      "type": "CVSS_V3",
      "score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:L/A:L"
    }
  ],
  "affected": [
    {
      "package": {
        "ecosystem": "PyPI",
        "name": "pyftpdlib"
      },
      "ranges": [
        {
          "type": "ECOSYSTEM",
          "events": [
            {
              "introduced": "0"
            },
            {
              "fixed": "0.5.0"
            }
          ]
        }
      ]
    }
  ],
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://nvd.nist.gov/vuln/detail/CVE-2008-7263"
    },
    {
      "type": "WEB",
      "url": "https://github.com/giampaolo/pyftpdlib/issues/73"
    },
    {
      "type": "PACKAGE",
      "url": "https://github.com/giampaolo/pyftpdlib"
    }
  ],
  "database_specific": {
    "cwe_ids": [
      "CWE-287"
    ],
    "severity": "HIGH",
    "github_reviewed": true
  }
}