{
  "schema_version": "1.2.0",
  "id": "GHSA-g57j-q48p-9vm2",
  "modified": "2021-10-20T22:28:57Z",
  "published": "2021-05-06T18:52:13Z",
  "aliases": [
    "CVE-2020-7698"
  ],
  "summary": "Command injection in Gerapy",
  "details": "This affects the package Gerapy from 0 and before 0.9.3. The input being passed to Popen, via the project_configure endpoint, isnâ€™t being sanitized.",
  "severity": [
    {
      "type": "CVSS_V3",
      "score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H"
    }
  ],
  "affected": [
    {
      "package": {
        "ecosystem": "PyPI",
        "name": "gerapy"
      },
      "ranges": [
        {
          "type": "ECOSYSTEM",
          "events": [
            {
              "introduced": "0"
            },
            {
              "fixed": "0.9.3"
            }
          ]
        }
      ]
    }
  ],
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://nvd.nist.gov/vuln/detail/CVE-2020-7698"
    },
    {
      "type": "WEB",
      "url": "https://github.com/Gerapy/Gerapy/commit/e8446605eb2424717418eae199ec7aad573da2d2"
    },
    {
      "type": "WEB",
      "url": "https://snyk.io/vuln/SNYK-PYTHON-GERAPY-572470"
    },
    {
      "type": "PACKAGE",
      "url": "https://github.com/Gerapy/Gerapy"
    }
  ],
  "database_specific": {
    "cwe_ids": [
      "CWE-74"
    ],
    "severity": "CRITICAL",
    "github_reviewed": true
  }
}