{
  "schema_version": "1.2.0",
  "id": "GHSA-cx59-cp6c-9fr8",
  "modified": "2022-06-08T22:33:05Z",
  "published": "2022-05-01T18:45:58Z",
  "aliases": [
    "CVE-2007-6740"
  ],
  "summary": "pyftpdlib vulnerable to allocation of resources without limits",
  "details": "The ftp_STOU function in FTPServer.py in pyftpdlib before 0.2.0 does not limit the number of attempts to discover a unique filename, which might allow remote authenticated users to cause a denial of service via a STOU command.",
  "severity": [
    {
      "type": "CVSS_V3",
      "score": "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:L"
    }
  ],
  "affected": [
    {
      "package": {
        "ecosystem": "PyPI",
        "name": "pyftpdlib"
      },
      "ranges": [
        {
          "type": "ECOSYSTEM",
          "events": [
            {
              "introduced": "0"
            },
            {
              "fixed": "0.2.0"
            }
          ]
        }
      ]
    }
  ],
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://nvd.nist.gov/vuln/detail/CVE-2007-6740"
    },
    {
      "type": "WEB",
      "url": "https://github.com/giampaolo/pyftpdlib/issues/25"
    },
    {
      "type": "PACKAGE",
      "url": "https://github.com/giampaolo/pyftpdlib"
    }
  ],
  "database_specific": {
    "cwe_ids": [
      "CWE-770"
    ],
    "severity": "MODERATE",
    "github_reviewed": true
  }
}