{
  "schema_version": "1.3.0",
  "id": "GHSA-h33x-58qw-vqrp",
  "modified": "2022-05-24T17:07:58Z",
  "published": "2022-05-24T17:07:58Z",
  "aliases": [
    "CVE-2019-9674"
  ],
  "details": "Lib/zipfile.py in Python through 3.7.2 allows remote attackers to cause a denial of service (resource consumption) via a ZIP bomb.",
  "severity": [

  ],
  "affected": [

  ],
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://nvd.nist.gov/vuln/detail/CVE-2019-9674"
    },
    {
      "type": "WEB",
      "url": "https://bugs.python.org/issue36260"
    },
    {
      "type": "WEB",
      "url": "https://bugs.python.org/issue36462"
    },
    {
      "type": "WEB",
      "url": "https://github.com/python/cpython/blob/master/Lib/zipfile.py"
    },
    {
      "type": "WEB",
      "url": "https://python-security.readthedocs.io/security.html#archives-and-zip-bomb"
    },
    {
      "type": "WEB",
      "url": "https://security.netapp.com/advisory/ntap-20200221-0003/"
    },
    {
      "type": "WEB",
      "url": "https://usn.ubuntu.com/4428-1/"
    },
    {
      "type": "WEB",
      "url": "https://www.python.org/news/security/"
    },
    {
      "type": "WEB",
      "url": "http://lists.opensuse.org/opensuse-security-announce/2020-03/msg00003.html"
    },
    {
      "type": "WEB",
      "url": "http://lists.opensuse.org/opensuse-security-announce/2020-05/msg00041.html"
    }
  ],
  "database_specific": {
    "cwe_ids": [

    ],
    "severity": "HIGH",
    "github_reviewed": false
  }
}