{
  "schema_version": "1.2.0",
  "id": "GHSA-fpfv-jqm9-f5jm",
  "modified": "2022-06-21T20:12:53Z",
  "published": "2021-12-18T00:00:41Z",
  "aliases": [
    "CVE-2021-34141"
  ],
  "summary": "Incorrect Comparison in NumPy",
  "details": "Incomplete string comparison in the numpy.core component in NumPy1.9.x, which allows attackers to fail the APIs via constructing specific string objects.",
  "severity": [
    {
      "type": "CVSS_V3",
      "score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:L"
    }
  ],
  "affected": [
    {
      "package": {
        "ecosystem": "PyPI",
        "name": "numpy"
      },
      "ranges": [
        {
          "type": "ECOSYSTEM",
          "events": [
            {
              "introduced": "0"
            },
            {
              "fixed": "1.22"
            }
          ]
        }
      ],
      "database_specific": {
        "last_known_affected_version_range": "<= 1.21.6"
      }
    }
  ],
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://nvd.nist.gov/vuln/detail/CVE-2021-34141"
    },
    {
      "type": "WEB",
      "url": "https://github.com/numpy/numpy/issues/18993"
    },
    {
      "type": "PACKAGE",
      "url": "https://github.com/numpy/numpy"
    }
  ],
  "database_specific": {
    "cwe_ids": [
      "CWE-697"
    ],
    "severity": "MODERATE",
    "github_reviewed": true
  }
}