{
  "schema_version": "1.4.0",
  "id": "GHSA-gfvq-mxw3-mfq3",
  "modified": "2023-10-03T06:30:26Z",
  "published": "2023-10-03T06:30:26Z",
  "aliases": [
    "CVE-2023-26151"
  ],
  "details": "Versions of the package asyncua before 0.9.96 are vulnerable to Denial of Service (DoS) such that an attacker can send a malformed packet and as a result, the server will enter into an infinite loop and consume excessive memory.",
  "severity": [
    {
      "type": "CVSS_V3",
      "score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:L"
    }
  ],
  "affected": [

  ],
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://nvd.nist.gov/vuln/detail/CVE-2023-26151"
    },
    {
      "type": "WEB",
      "url": "https://github.com/FreeOpcUa/opcua-asyncio/issues/1013"
    },
    {
      "type": "WEB",
      "url": "https://github.com/FreeOpcUa/opcua-asyncio/pull/1039"
    },
    {
      "type": "WEB",
      "url": "https://github.com/FreeOpcUa/opcua-asyncio/commit/f6603daa34a93a658f0e176cb0b9ee5a6643b262"
    },
    {
      "type": "WEB",
      "url": "https://gist.github.com/artfire52/1540b234350795e0ecb4d672608dbec8"
    },
    {
      "type": "WEB",
      "url": "https://github.com/FreeOpcUa/opcua-asyncio/releases/tag/v0.9.96"
    },
    {
      "type": "WEB",
      "url": "https://security.snyk.io/vuln/SNYK-PYTHON-ASYNCUA-5673709"
    }
  ],
  "database_specific": {
    "cwe_ids": [

    ],
    "severity": null,
    "github_reviewed": false,
    "github_reviewed_at": null,
    "nvd_published_at": null
  }
}